"use client";

import styles from "../learn.module.css";
import { useUiLanguage } from "../../../lib/use-ui-language";

export default function Tutor(){
  const ru=useUiLanguage()==="ru";
  const prompts=ru?["Объясни мой текущий урок","Потренируем реальный разговор","Проведи тест на 5 минут","Разбери мои ошибки","Произношение и аудирование","Подготовь к следующему уроку"]:["Explain my current lesson","Practice a real conversation","Quiz me for 5 minutes","Review my mistakes","Pronunciation & listening","Prepare for the next lesson"];
  return <>
    <div className={styles.pageHeading}><span className={styles.eyebrow}>AIRA TUTOR</span><h1>{ru?"Практикуй именно то, что нужно тебе сегодня":"Practice in the way you need today"}</h1><p>{ru?"AIRA учитывает изучаемый язык, уровень и текущий учебный контекст, чтобы объяснения были понятными, а практика — полезной.":"AIRA uses your language, level and learning context to keep explanations understandable and practice relevant."}</p></div>
    <section className={styles.tutorHero}><div className={styles.aiOrb}>A</div><div><span className={styles.pill}>{ru?"Персональный tutor · пространство ученика":"Personal tutor · student workspace"}</span><h2>{ru?"Выбери режим практики":"Choose a practice mode"}</h2><p>{ru?"Помощь по уроку, разговор, быстрый повтор и голосовая практика разделены на отдельные режимы с понятной целью.":"Lesson help, conversation, quick review and voice practice are separated into focused modes."}</p><div className={styles.promptGrid}>{prompts.map(item=><button key={item}>{item}</button>)}</div></div></section>
    <section className={styles.twoColumn}><article className={styles.panel}><span className={styles.eyebrow}>{ru?"ТЕКСТОВЫЙ TUTOR":"TEXT TUTOR"}</span><h2>{ru?"Спрашивай на удобном тебе языке":"Ask in your own language"}</h2><p>{ru?"AIRA может упростить грамматику, привести примеры, перевести контекст и отрепетировать бытовую ситуацию, не заставляя тебя пользоваться английским интерфейсом.":"AIRA can simplify grammar, create examples, translate context and rehearse everyday situations without forcing the interface language to English."}</p><span className={styles.pill}>{ru?"Основа с учётом контекста":"Context-aware foundation"}</span></article><article className={styles.darkPanel}><span className={styles.eyebrow}>VOICE TUTOR</span><h2>{ru?"Разговорная практика":"Conversation practice"}</h2><p>{ru?"Голосовой режим предназначен для произношения, аудирования и живого диалога. Полноценный voice runtime подключим отдельным этапом.":"The voice workspace is for pronunciation, listening and spoken dialogue. Full voice runtime will be connected in a later stage."}</p><button className={styles.lightButton}>{ru?"Предпросмотр голосового режима":"Voice mode preview"}</button></article></section>
  </>;
}
