import Link from "next/link";
import styles from "./learn.module.css";

export default function LearningDashboard() {
  return <>
    <section className={styles.hero}><div><span className={styles.eyebrow}>ТВОЁ УЧЕБНОЕ ПРОСТРАНСТВО</span><h1>С возвращением, Кристина</h1><p>Продолжай развивать разговорный английский вместе с AIRA. Следующий урок уже готов.</p></div><Link className={styles.primaryButton} href="/learn/tutor">Спросить AIRA</Link></section>
    <section className={styles.section}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>ПРОДОЛЖИТЬ ОБУЧЕНИЕ</span><h2>Продолжи с того места, где остановилась</h2></div><Link href="/learn/courses">Моё обучение</Link></div><div className={styles.featureCard}><div className={styles.courseIcon}>🇺🇸</div><div className={styles.featureBody}><span className={styles.pill}>Разговорный английский · A1</span><h3>Знакомство и рассказ о себе</h3><p>Практика первой естественной беседы: имя, откуда ты, чем занимаешься и простой встречный вопрос.</p><div className={styles.progressRow}><div className={styles.progress}><i style={{width:"50%"}} /></div><span>50%</span></div></div><Link className={styles.primaryButton} href="/learn/courses">Продолжить урок</Link></div></section>
    <section className={styles.statsGrid}><article><span>Прогресс курса</span><strong>50%</strong><small>Пройден 1 из 2 уроков</small></article><article><span>Серия обучения</span><strong>4 дня</strong><small>Лучший результат этой недели</small></article><article><span>Цель на день</span><strong>20 мин</strong><small>Сегодня выполнено 12 минут</small></article><article><span>Активные курсы</span><strong>1</strong><small>Доступно 3 курса</small></article></section>
    <section className={styles.twoColumn}><article className={styles.panel}><span className={styles.eyebrow}>ТВОЙ ПУТЬ</span><h2>Следующий рекомендованный урок</h2><div className={styles.lessonRow}><div><strong>02</strong></div><div><h3>Знакомство и рассказ о себе</h3><p>Примерное время · 10 мин</p></div><span className={styles.pill}>Готов</span></div><Link className={styles.textLink} href="/learn/courses">Открыть учебный путь →</Link></article><article className={styles.darkPanel}><span className={styles.eyebrow}>AIRA TUTOR</span><h2>Практика с AIRA</h2><p>Попроси объяснить тему, потренируй диалог или подготовься к следующему уроку.</p><Link className={styles.lightButton} href="/learn/tutor">Начать сессию Tutor</Link></article></section>
  </>;
}
