import Link from "next/link";
import styles from "./learn.module.css";

export default function LearningDashboard() {
  return <>
    <section className={styles.hero}><div><span className={styles.eyebrow}>THURSDAY · YOUR LEARNING SPACE</span><h1>Welcome back, Kristina</h1><p>Continue building confident English with AIRA. Your next lesson is ready.</p></div><Link className={styles.primaryButton} href="/learn/tutor">Ask AIRA</Link></section>
    <section className={styles.section}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>CONTINUE LEARNING</span><h2>Pick up where you left off</h2></div><Link href="/learn/courses">View learning</Link></div><div className={styles.featureCard}><div className={styles.courseIcon}>EN</div><div className={styles.featureBody}><span className={styles.pill}>Conversational English · A1</span><h3>Introducing yourself</h3><p>Practice a natural first conversation: your name, where you are from, and a simple follow-up question.</p><div className={styles.progressRow}><div className={styles.progress}><i style={{width:"50%"}} /></div><span>50%</span></div></div><Link className={styles.primaryButton} href="/learn/courses">Continue lesson</Link></div></section>
    <section className={styles.statsGrid}><article><span>Course progress</span><strong>50%</strong><small>1 of 2 lessons completed</small></article><article><span>Learning streak</span><strong>4 days</strong><small>Personal best this week</small></article><article><span>Daily target</span><strong>20 min</strong><small>12 minutes completed today</small></article><article><span>Active courses</span><strong>1</strong><small>3 courses available</small></article></section>
    <section className={styles.twoColumn}><article className={styles.panel}><span className={styles.eyebrow}>YOUR PATH</span><h2>Next recommended lesson</h2><div className={styles.lessonRow}><div><strong>02</strong></div><div><h3>Introducing yourself</h3><p>Estimated time · 10 min</p></div><span className={styles.pill}>Ready</span></div><Link className={styles.textLink} href="/learn/courses">Open learning path →</Link></article><article className={styles.darkPanel}><span className={styles.eyebrow}>AI TUTOR</span><h2>Practice with AIRA</h2><p>Ask for an explanation, rehearse a conversation, or prepare for your next lesson.</p><Link className={styles.lightButton} href="/learn/tutor">Start a tutor session</Link></article></section>
  </>;
}
