from enum import StrEnum


class ContentStatus(StrEnum):
    IDEA = "IDEA"
    RESEARCH_REQUIRED = "RESEARCH_REQUIRED"
    BRIEF = "BRIEF"
    DRAFT = "DRAFT"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    GUARDIAN_REVIEW = "GUARDIAN_REVIEW"
    FOUNDER_REVIEW = "FOUNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    READY_TO_PUBLISH = "READY_TO_PUBLISH"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


class ClaimKind(StrEnum):
    FACT = "FACT"
    TEST_RESULT = "TEST_RESULT"
    AIRA_OPINION = "AIRA_OPINION"
    ESTIMATE = "ESTIMATE"
    PREDICTION = "PREDICTION"
    UNVERIFIED_INFORMATION = "UNVERIFIED_INFORMATION"


class ReviewStatus(StrEnum):
    NOT_REQUESTED = "NOT_REQUESTED"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVISION_REQUIRED = "REVISION_REQUIRED"


class DuplicateDecision(StrEnum):
    CREATE = "CREATE"
    UPDATE_EXISTING = "UPDATE_EXISTING"
    CREATE_FOLLOW_UP = "CREATE_FOLLOW_UP"
    MERGE = "MERGE"
    SKIP = "SKIP"


class FounderAction(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_REVISION = "REQUEST_REVISION"
    SAVE_FOR_LATER = "SAVE_FOR_LATER"
