export const metrics=[['Active Agents','8','All healthy'],['Pending Approvals','3','2 high priority'],['Running Workflows','5','1 waiting'],['Research Today','12','3 high-value'],['Knowledge Updates','7','Since midnight'],['Content Drafts','4','2 ready for review'],['Scheduled','1','Today · 16:00'],['API Cost Today','$42.18','63% of daily budget']];
export const pages:{[key:string]:{title:string;subtitle:string;columns:string[];rows:string[][]}}={
approvals:{title:'Approval Center',subtitle:'Evidence-first decisions waiting for Founder review',columns:['Request','Type','Requested by','Risk','Guardian','Created'],rows:[['APR-2041','Content Approval','Content Agent','HIGH','APPROVED','09:14'],['APR-2040','Publishing Approval','Publishing Agent','MEDIUM','APPROVED','08:52'],['APR-2038','Agent Permission','Research Agent','HIGH','REVIEWED','Yesterday']]},
agents:{title:'Agent Registry',subtitle:'Health, autonomy, permissions, activity and spend',columns:['Agent','Type','Status','Health','Current task','Autonomy','Cost today'],rows:[['Research Agent','RESEARCH','ACTIVE','HEALTHY','RS-882: tool landscape','SUPERVISED','$12.40'],['Content Agent','CONTENT','ACTIVE','HEALTHY','Drafting CNT-410','SUPERVISED','$8.20'],['Publishing Agent','PUBLISHING','PAUSED','HEALTHY','—','APPROVAL_ONLY','$1.10']]},
research:{title:'Research',subtitle:'Fresh findings with provenance, confidence and conflicts',columns:['Finding','Source type','Trust','Confidence','Freshness','Status'],rows:[['Model context protocol update','Primary docs','HIGH','94%','2h','VERIFIED'],['Enterprise agent trend','Industry report','MEDIUM','78%','5h','UNVERIFIED'],['New multimodal benchmark','Research paper','HIGH','88%','1d','CONFLICT']]},
knowledge:{title:'Knowledge',subtitle:'Inspectable nodes and relationships — no hidden conclusions',columns:['Node','Category','Confidence','Updated','Relationships','Status'],rows:[['Claude','AI Tool','92%','Today','18','CURRENT'],['GPT-5','AI Model','89%','Today','24','CURRENT'],['Legacy vector stack','Architecture','71%','Jul 18','7','DEPRECATED']]},
memory:{title:'Memory',subtitle:'Project-level memory with provenance and version history',columns:['Memory ID','Type','Summary','Confidence','Importance','Version','Archive'],rows:[['MEM-1028','DECISION','Prioritize evidence-first approvals','97%','HIGH','v3','ACTIVE'],['MEM-1021','PROJECT','Sprint 013 scope','100%','HIGH','v1','ACTIVE'],['MEM-995','RESEARCH','Agent reliability observations','83%','MEDIUM','v2','ACTIVE']]},
content:{title:'Content',subtitle:'Ideas, drafts and approved versions across the content lifecycle',columns:['Title','Platform','Type','Version','Stage','Risk','Owner'],rows:[['AI agents need supervision','LinkedIn','Post','v4','FOUNDER REVIEW','HIGH','Content Agent'],['Weekly research brief','Newsletter','Brief','v2','GUARDIAN REVIEW','MEDIUM','Content Agent'],['Tool comparison framework','Blog','Article','v1','DRAFT','LOW','Content Agent']]},
workflows:{title:'Workflows',subtitle:'Plans, dependencies, progress and next actions',columns:['Workflow','Goal','Current stage','Progress','Assigned','ETA','Status'],rows:[['WF-882','Publish agent safety insight','Founder Approval','74%','3 agents','Today','BLOCKED'],['WF-879','Refresh tool knowledge','Knowledge','48%','2 agents','3h','RUNNING'],['WF-870','Weekly briefing','Complete','100%','4 agents','—','COMPLETED']]},
publishing:{title:'Publishing',subtitle:'Controlled outbound queue — publishing is currently paused',columns:['Publication','Platform','Version','Schedule','Attempts','Guardian','Status'],rows:[['PUB-510','LinkedIn','CNT-410 v3','Today 16:00','0','APPROVED','SCHEDULED'],['PUB-508','Newsletter','CNT-405 v2','Tomorrow 09:00','0','APPROVED','QUEUED'],['PUB-501','Blog','CNT-399 v5','Aug 8','1','APPROVED','PUBLISHED']]},
incidents:{title:'Incidents',subtitle:'Operational issues, timelines, causes and resolution',columns:['Incident','Severity','Type','Affected system','Opened','Owner','Status'],rows:[['INC-104','MEDIUM','PROVIDER_TIMEOUT','Research','Yesterday','System','MONITORING'],['INC-102','LOW','STALE_SOURCE','Knowledge','Aug 7','Knowledge Agent','RESOLVED']]},
costs:{title:'Costs & Budgets',subtitle:'Transparent usage across providers, agents and workflows',columns:['Provider','Today','This week','This month','Budget usage','Trend'],rows:[['OpenAI','$22.41','$118.20','$391.80','61%','↑ 4%'],['Anthropic','$14.20','$82.10','$280.40','54%','↓ 2%'],['Gemini','$5.57','$31.40','$102.10','29%','→'],['Hosting','$3.12','$21.84','$93.60','47%','→']]},
settings:{title:'Settings',subtitle:'Future-safe configuration — secret values are never displayed',columns:['Service','Configuration','Last updated','Scope','Status'],rows:[['OpenAI','•••••• configured','Aug 4','Models','CONFIGURED'],['Anthropic','•••••• configured','Aug 4','Models','CONFIGURED'],['LinkedIn','No credential value shown','Jul 29','Publishing','CONFIGURED'],['Daily budget','$67.00','Today','Costs','ACTIVE']]}}
