"""Ports implemented by infrastructure; secrets are references, never values."""

from typing import Any, Protocol
from ..domain.models import *


class PublishingRepository(Protocol):
    def get(self, publication_id: str) -> Publication | None: ...
    def save(self, publication: Publication) -> None: ...

class PublishingQueue(Protocol):
    def enqueue(self, publication_id: str, scheduled_at=None) -> None: ...
    def next(self) -> str | None: ...
    def cancel(self, publication_id: str) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...

class PlatformAdapter(Protocol):
    name: str
    def validate(self, publication: Publication, content: ContentSnapshot) -> None: ...
    def prepare(self, publication: Publication, content: ContentSnapshot) -> Any: ...
    def publish(self, prepared: Any, idempotency_key: str) -> AdapterResult: ...
    def health_check(self) -> bool: ...

class CredentialProvider(Protocol):
    def is_available(self, credential_reference: str) -> bool: ...

class ApprovalValidator(Protocol):
    def validate(self, publication: Publication, content: ContentSnapshot) -> None: ...

class MediaRepository(Protocol):
    def get(self, asset_id: str) -> MediaAsset | None: ...

class AuditRepository(Protocol):
    def append(self, event: AuditEvent) -> None: ...

class EventPublisher(Protocol):
    def publish(self, event_type: str, payload: dict[str, Any]) -> None: ...

class Clock(Protocol):
    def now(self): ...

class IdempotencyStore(Protocol):
    def claim(self, key: str, publication_id: str) -> bool: ...
    def complete(self, key: str, receipt: PublicationReceipt) -> None: ...
    def receipt(self, key: str) -> PublicationReceipt | None: ...
