from __future__ import annotations

from typing import Any, Protocol
from .models import ConversationSession, TelegramMessage


class AiraCore(Protocol):
    """Platform-neutral AIRA orchestration boundary."""
    def respond(self, message: TelegramMessage, session: ConversationSession, context: list[dict]) -> str: ...
    def status(self) -> dict[str, Any]: ...
    def tasks(self) -> list[dict[str, Any]]: ...
    def research(self, query: str, session: ConversationSession) -> str: ...
    def cancel(self, session: ConversationSession) -> bool: ...


class Perception(Protocol):
    def understand(self, path: str, media_type: str, caption: str) -> str: ...


class SpeechEngine(Protocol):
    def transcribe(self, path: str) -> str: ...
    def synthesize(self, text: str) -> str: ...


class Memory(Protocol):
    def recent(self, session_id: str, limit: int = 20) -> list[dict]: ...
    def consider(self, session_id: str, role: str, text: str) -> None: ...
