import Link from "next/link";

const modules = [
  {title:"Ученики",status:"Нет данных",desc:"Аккаунты, языки, уровни, прогресс, streak и статусы доступа.",href:"/developer/students"},
  {title:"Аналитика обучения",status:"Ожидает cloud progress",desc:"Завершение уроков, drop-off, языки, уровни и эффективность курсов.",href:"/developer/analytics"},
  {title:"Content Studio",status:"Рабочие статусы",desc:"Управление учебным контентом и workflow Draft → Review → Published.",href:"/developer/content"},
  {title:"AIRA Tutor & Voice",status:"Рабочая зона",desc:"Проверка Tutor, lesson context, voice readiness и качества учебных ответов.",href:"/developer/tutor"},
  {title:"Сайт и деплои",status:"Runtime health",desc:"Production, health и технические проверки сайта.",href:"/developer/site"},
  {title:"Платежи",status:"Не подключено",desc:"Тарифы, подписки, платежи и выручка после запуска коммерции.",href:"/developer#billing"},
  {title:"Безопасность и аудит",status:"Рабочая зона",desc:"Owner access, закрытые маршруты, сессии и будущий audit log.",href:"/developer/security"},
  {title:"Настройки Academy",status:"Founder config",desc:"Глобальный язык, AI-функции, лимиты и режимы платформы.",href:"/developer/settings"},
];

export default function FounderConsole(){
  return <main>
    <div className="page-head"><div><p className="eyebrow">AIRA OS · КАБИНЕТ ОСНОВАТЕЛЯ</p><h1>Центр управления</h1><p className="muted">Единое рабочее пространство для Academy, учеников, контента, AI-систем и сайта.</p></div><div><span className="health">● OWNER MODE</span><form action="/api/developer/logout" method="post" style={{marginTop:12}}><button className="button" type="submit">Выйти</button></form></div></div>
    <section className="brief"><div><span className="eyebrow">LIVE OPERATIONS</span><h2>Управление платформой без выдуманных показателей.</h2><span>Если источник данных ещё не подключён, кабинет показывает «Нет данных» или «Не подключено».</span></div><Link className="button" href="/academy">Открыть Academy →</Link></section>
    <div className="grid"><article className="card metric"><span className="eyebrow">УЧЕНИКИ</span><div className="value">0</div><span className="muted">Cloud storage ещё не подключено</span></article><article className="card metric"><span className="eyebrow">ЗАВЕРШЁННЫЕ УРОКИ</span><div className="value">0</div><span className="muted">Ожидаются server-side progress events</span></article><article className="card metric"><span className="eyebrow">ЯЗЫКИ</span><div className="value">10</div><span className="trend">Каталог Academy активен</span></article><article className="card metric"><span className="eyebrow">ПЛАТФОРМА</span><div className="value">Online</div><span className="trend">Production доступен</span></article></div>
    <div className="section-head"><h2>Быстрые действия</h2><span className="muted">Рабочие инструменты основателя</span></div><div className="controls"><Link href="/developer/students" className="button">Ученики</Link><Link href="/developer/analytics" className="button">Аналитика</Link><Link href="/developer/content" className="button">Content Studio</Link><Link href="/developer/tutor" className="button">AIRA Tutor & Voice</Link><Link href="/developer/site" className="button">Сайт и деплои</Link><Link href="/developer/security" className="button">Безопасность</Link><Link href="/developer/settings" className="button">Настройки Academy</Link></div>
    <div className="section-head"><h2>Операционные модули</h2><span className="muted">AIRA Academy control surface</span></div><div className="grid">{modules.map(item=><article className="card" key={item.title}><span className="pill">{item.status}</span><h2>{item.title}</h2><p className="muted">{item.desc}</p><Link href={item.href}>Открыть →</Link></article>)}</div>
    <div className="two-col" style={{marginTop:28}}><section className="card"><span className="eyebrow">СТАТУС СИСТЕМЫ</span><h2>Academy services</h2><div className="attention"><span className="dot"/><div><strong>Student cloud storage</strong><span className="muted">Не подключено — API boundary подготовлен.</span></div></div><div className="attention"><span className="dot"/><div><strong>Learning analytics</strong><span className="muted">Ожидает серверных learner events.</span></div></div><div className="attention"><span className="dot red"/><div><strong>Billing</strong><span className="muted">Не настроен. Платный доступ пока не активен.</span></div></div><div className="attention"><span className="dot"/><div><strong>AIRA Academy production</strong><span className="muted">Сайт доступен через production deployment.</span></div></div></section><section className="card"><span className="eyebrow">СЛЕДУЮЩИЕ ПОДКЛЮЧЕНИЯ</span><h2>Founder roadmap</h2><p><strong>1.</strong> Student identity + database</p><p><strong>2.</strong> Real learner analytics</p><p><strong>3.</strong> Server-side content registry</p><p><strong>4.</strong> Tutor/Voice quality telemetry</p><p><strong>5.</strong> Billing telemetry</p><p><strong>6.</strong> Security/audit history</p></section></div>
  </main>
}
