"""Data models for the Sprint 007 Planner Engine architecture.

These models are intentionally execution-free. They describe goals, tasks,
workflows, approvals, dependency relationships, and progress snapshots so that
execution agents can act only after founder approval.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4


def utc_now() -> datetime:
    """Return an aware UTC timestamp for model audit fields."""

    return datetime.now(timezone.utc)


class GoalType(str, Enum):
    CONTENT = "content"
    RESEARCH = "research"
    BUSINESS = "business"
    DEVELOPMENT = "development"
    MARKETING = "marketing"
    LEARNING = "learning"
    MAINTENANCE = "maintenance"
    AUTOMATION = "automation"
    PROJECT = "project"
    PERSONAL = "personal"


class PlanningLevel(int, Enum):
    SINGLE_TASK = 1
    PROJECT = 2
    INITIATIVE = 3
    STRATEGIC_OBJECTIVE = 4


class Priority(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    SOMEDAY = "someday"


class TaskStatus(str, Enum):
    DRAFT = "draft"
    PLANNED = "planned"
    WAITING_APPROVAL = "waiting_approval"
    QUEUED = "queued"
    IN_PROGRESS = "in_progress"
    BLOCKED = "blocked"
    REVIEW = "review"
    COMPLETED = "completed"
    ARCHIVED = "archived"
    CANCELLED = "cancelled"


class PlanStatus(str, Enum):
    DRAFT = "draft"
    WAITING_GUARDIAN_REVIEW = "waiting_guardian_review"
    WAITING_FOUNDER_APPROVAL = "waiting_founder_approval"
    APPROVED = "approved"
    REJECTED = "rejected"
    ARCHIVED = "archived"


class ExecutionStrategy(str, Enum):
    SEQUENTIAL = "sequential"
    PARALLEL = "parallel"
    CONDITIONAL = "conditional"
    MANUAL = "manual"
    SCHEDULED = "scheduled"
    HYBRID = "hybrid"


@dataclass(frozen=True)
class AgentCapability:
    """Available agent role and responsibilities for assignment decisions."""

    name: str
    responsibilities: tuple[str, ...]
    max_parallel_tasks: int = 1


@dataclass
class ComplexityEstimate:
    """Planning estimate for a task or whole plan."""

    estimated_duration_minutes: int
    difficulty: int
    risk: int
    confidence: float
    resource_usage: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.estimated_duration_minutes < 0:
            raise ValueError("estimated_duration_minutes cannot be negative")
        if not 1 <= self.difficulty <= 5:
            raise ValueError("difficulty must be between 1 and 5")
        if not 1 <= self.risk <= 5:
            raise ValueError("risk must be between 1 and 5")
        if not 0 <= self.confidence <= 1:
            raise ValueError("confidence must be between 0 and 1")


@dataclass
class Task:
    """Execution-free task object generated by the Planner Engine."""

    title: str
    description: str
    priority: Priority
    owner: str
    agent: str
    estimate: ComplexityEstimate
    task_id: str = field(default_factory=lambda: f"task_{uuid4().hex[:12]}")
    status: TaskStatus = TaskStatus.DRAFT
    dependencies: set[str] = field(default_factory=set)
    business_value: int = 3
    deadline: datetime | None = None
    created_date: datetime = field(default_factory=utc_now)
    updated_date: datetime = field(default_factory=utc_now)
    history: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not 1 <= self.business_value <= 5:
            raise ValueError("business_value must be between 1 and 5")
        if self.task_id in self.dependencies:
            raise ValueError("task cannot depend on itself")

    def transition(self, status: TaskStatus, note: str) -> None:
        self.status = status
        self.updated_date = utc_now()
        self.history.append(f"{self.updated_date.isoformat()} {status.value}: {note}")


@dataclass(frozen=True)
class Goal:
    """Founder or engine request to be transformed into a plan."""

    title: str
    objective: str
    goal_type: GoalType
    level: PlanningLevel
    source: str = "founder_request"
    goal_id: str = field(default_factory=lambda: f"goal_{uuid4().hex[:12]}")
    constraints: tuple[str, ...] = ()
    success_criteria: tuple[str, ...] = ()
    created_date: datetime = field(default_factory=utc_now)


@dataclass(frozen=True)
class Workflow:
    """Named workflow template or generated workflow graph."""

    name: str
    strategy: ExecutionStrategy
    phases: tuple[str, ...]
    approval_required: bool = True


@dataclass(frozen=True)
class DependencyIssue:
    """Dependency validation issue detected before queueing."""

    code: str
    message: str
    task_id: str | None = None


@dataclass
class ExecutionPlan:
    """Structured plan produced by the Planner Engine."""

    goal: Goal
    tasks: list[Task]
    workflow: Workflow
    plan_id: str = field(default_factory=lambda: f"plan_{uuid4().hex[:12]}")
    status: PlanStatus = PlanStatus.DRAFT
    created_date: datetime = field(default_factory=utc_now)
    updated_date: datetime = field(default_factory=utc_now)
    dependency_issues: list[DependencyIssue] = field(default_factory=list)
    roadmap_updates: list[str] = field(default_factory=list)

    def task_map(self) -> dict[str, Task]:
        return {task.task_id: task for task in self.tasks}

    def request_founder_approval(self) -> None:
        self.status = PlanStatus.WAITING_FOUNDER_APPROVAL
        self.updated_date = utc_now()
        for task in self.tasks:
            task.transition(TaskStatus.WAITING_APPROVAL, "Plan awaits founder approval")

    def approve(self) -> None:
        self.status = PlanStatus.APPROVED
        self.updated_date = utc_now()
        for task in self.tasks:
            if task.status == TaskStatus.WAITING_APPROVAL:
                task.transition(TaskStatus.QUEUED, "Founder approved plan")

    def reject(self, reason: str) -> None:
        self.status = PlanStatus.REJECTED
        self.updated_date = utc_now()
        for task in self.tasks:
            task.transition(TaskStatus.CANCELLED, f"Plan rejected: {reason}")


@dataclass(frozen=True)
class ProgressReport:
    """Progress snapshot for monitoring approved plans."""

    plan_id: str
    completed: int
    remaining: int
    blocked: int
    delayed: int
    risk: float
    velocity: float
    forecast: str
